// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjjEObmoeN1ChINSVfyqq1FYEDSzXo-Yk',
    appId: '1:88153710264:web:590d291ef9ea8d5c0ede4d',
    messagingSenderId: '88153710264',
    projectId: 'expense-tracker-211eb',
    authDomain: 'expense-tracker-211eb.firebaseapp.com',
    storageBucket: 'expense-tracker-211eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yOQ2QvkLfkQga6J5QTJ2YW7oXgu4Gow',
    appId: '1:88153710264:android:d2399c8ebc9511430ede4d',
    messagingSenderId: '88153710264',
    projectId: 'expense-tracker-211eb',
    storageBucket: 'expense-tracker-211eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBUkHZd4CV-vxg2nHuRoncDJeutV21U8',
    appId: '1:88153710264:ios:d477bdf7b160dd620ede4d',
    messagingSenderId: '88153710264',
    projectId: 'expense-tracker-211eb',
    storageBucket: 'expense-tracker-211eb.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVBUkHZd4CV-vxg2nHuRoncDJeutV21U8',
    appId: '1:88153710264:ios:5cab0ce07870c1000ede4d',
    messagingSenderId: '88153710264',
    projectId: 'expense-tracker-211eb',
    storageBucket: 'expense-tracker-211eb.appspot.com',
    iosBundleId: 'com.example.expensesTracker.RunnerTests',
  );
}
